name: Start Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  start-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Start frontend
      run: npm start-fe
    - name: Start backend
      run: npm npm start-be
    - name: Run tests
      run: npm npm start-be
